# Some fundamentals for tensorflow


---
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using `tf.function`
* Using GPUs And TPUs 



### Introductions to Tensors


In [1]:
# Imort Tensorflow
import tensorflow as tf


print(tf.__version__)

2.4.1


In [2]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# View number of tensor dimensions
# `ndim`
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[10,10],
                      [8,8]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 8,  8]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create a float matrix
another_matrix = tf.constant([[10. , 8,],
                              [5. , 6.],
                              [9. , 7.]],dtype=tf.float16) 
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  8.],
       [ 5.,  6.],
       [ 9.,  7.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Lets now create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,17]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 17]]], dtype=int32)>

In [11]:
tensor.ndim

3

#### What we have created so far:
* Scalar: A single number
* Vector: A number with directions
* Matrix: A 2-dimensional array of numbers
* Tensor: A n-dimensional array of numbers

### Creating tensors with `tf.Variable`

In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [14]:
# Lets create a changeable tensor

changeable_tensor = tf.Variable([10,10])

unchangeable_tensor = tf.constant([10,10])

In [15]:
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [17]:
# Now lets try changing one of the elements in our changeable tensor

# changeable_tensor[0] = 7 Wont work since is does not support item assignment

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

**Note:** Usually we wont need to decide between `tf.constant` and `tf.Variable` since tensorflow does this on its own.

### Creating Random Tensors